"""New table User

Revision ID: 3a005bc70a68
Revises: dec050ee31f5
Create Date: 2023-11-18 01:11:57.827848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a005bc70a68'
down_revision: Union[str, None] = 'dec050ee31f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Table', 'User', ['tgid'], ['tgid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Table', type_='foreignkey')
    # ### end Alembic commands ###
