"""New table User

Revision ID: b5fb6b7818f0
Revises: 3a005bc70a68
Create Date: 2023-11-18 01:42:08.755826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5fb6b7818f0'
down_revision: Union[str, None] = '3a005bc70a68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Table_tgid_fkey', 'Table', type_='foreignkey')
    op.create_foreign_key(None, 'Table', 'User', ['tgid'], ['tgid'], onupdate='cascade', ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Table', type_='foreignkey')
    op.create_foreign_key('Table_tgid_fkey', 'Table', 'User', ['tgid'], ['tgid'])
    # ### end Alembic commands ###
