"""New table User

Revision ID: c2cee86db506
Revises: 
Create Date: 2023-11-18 00:53:48.381566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2cee86db506'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('tgid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('need_notif', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('tgid')
    )
    op.alter_column('Table', 'tgid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Table', 'day_of_week',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.alter_column('Table', 'timestart',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
    op.alter_column('Table', 'event',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_Table_id'), 'Table', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Table_id'), table_name='Table')
    op.alter_column('Table', 'event',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Table', 'timestart',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
    op.alter_column('Table', 'day_of_week',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('Table', 'tgid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('User')
    # ### end Alembic commands ###
