"""Update table TABLE

Revision ID: c9cf7cdef066
Revises: b5fb6b7818f0
Create Date: 2023-11-28 01:26:03.195362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9cf7cdef066'
down_revision: Union[str, None] = 'b5fb6b7818f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
